export type Language = 'zh' | 'en';

export const TRANSLATIONS = {
  zh: {
    // App Header & Layout
    app_subtitle: '支持标准/径向变位直齿轮数学建模，提供轻量化镂空腔体与割缝尺寸膨胀补偿，支持激光加工 1:1 SVG 矢量文件下载',
    app_cad_ready: 'CAD_READY_TO_EXPORT (公制物理级标定)',
    app_formula_ref: '🌐 渐开线齿物理几何公式参考',
    app_formula_pitch: '分度圆直径：',
    app_formula_pitch_desc: ' (标准齿轮齿部基准依据)',
    app_formula_base: '基圆直径：',
    app_formula_base_desc: ' (决定渐开线型线的展成轨迹基准)',
    app_formula_addendum: '齿顶圆直径：',
    app_formula_addendum_desc: ' (齿廓最外围边缘界线)',
    app_formula_dedendum: '齿根圆直径：',
    app_formula_dedendum_desc: ' (轮齿槽底部最低圈)',
    app_purpose_shift: '⚙️ 变位齿轮 (Profile Shift) 功用',
    app_purpose_text: '当齿轮齿数较少（如 z < 17）时，标准齿轮滚法加工会导致由于刀具干涉削弱轮轴强度，即所谓的 “齿根根切”，极大降低轮齿抗剪折弯极限。在此系统里，通过设置 正径向变位系数 x > 0 ，你能观察到齿顶、齿分度圆以及渐开线物理向外侧生长，增大了轮齿根基厚度，从而从根本上消除弱切损害，优化整体轮齿强度与磨损。',
    app_copyright: '© 2026 高精度齿轮几何发生引擎. 本在线工具对数学公式结果负责，请在导入高速重载切削床前自测验证。',

    // GearViewer Component
    gv_title: '核心实况物理视图',
    gv_mating_linkage: '副轮联动:',
    gv_pause: '暂停运动',
    gv_simulate: '仿真旋转',
    gv_zoom: '缩放:',
    gv_zoom_in: '放大视图',
    gv_zoom_out: '缩小视图',
    gv_reset_view: '自适应视图居中',
    gv_primary_pitch: '主齿分度圆:',
    gv_primary_tip: '主齿顶直径:',
    gv_mating_tip: '副齿顶直径:',
    gv_center_dist: '中心轴距:',
    gv_move_hint: '支持鼠标拖拽位移、滚轮/手机手指捏合双指缩放',

    // StatsPanel Component
    sp_title: '齿轮工程尺寸计算',
    sp_warning_title: '⚠️ 根切风险警告 (Undercut Warning)',
    sp_warning_text: '当前齿数 z = {teeth} 小于非变位不根切的最极限齿数 {limit}。这会导致刀具在切入时削弱齿根弧度，减少齿根抗弯曲强度，同时降低接触传动平顺度。',
    sp_suggestion_title: '💡 工艺修正建议：',
    sp_suggestion_shift: '设置正径向变位系数 x ≥ ',
    sp_suggestion_teeth: '或者将齿轮齿齿数增加至不少于 ',
    sp_strength_ok: '齿廓强度状态：良好',
    sp_strength_ok_desc: '齿剖面避开了加工根切区，齿根肉厚度适中，能承受理想的齿向载荷强度。',
    sp_heading_radial: '● 轮廓径向圈尺寸',
    sp_tip_dia: '齿顶圆直径 da',
    sp_tip_dia_desc: '齿轮最外层的直径圆柱面，da = d + 2 * (ha* + x) * m',
    sp_pitch_dia: '分度圆直径 d',
    sp_pitch_dia_desc: '齿轮的几何参考设计圈，d = m * z',
    sp_base_dia: '基圆直径 db',
    sp_base_dia_desc: '生成渐开线所包络的底圆柱面，db = d * cos(alpha)',
    sp_dedendum_dia: '齿根圆直径 df',
    sp_dedendum_dia_desc: '轮齿槽最底侧的底面圆，df = d - 2 * (ha* + c* - x) * m',
    sp_heading_micro: '● 轮齿微观物理几何',
    sp_tooth_thickness: '分度圆齿厚 s (Arc Thickness)',
    sp_circular_pitch: '端面圆周齿距 p (Circular Pitch)',
    sp_base_pitch: '基圆齿距 pb (Base Pitch)',
    sp_total_height: '单齿高度 h (Total Tooth Height)',

    // ParameterPanel Component
    pp_title: '齿轮参数设置',
    pp_btn_reset: '重置为标准齿轮',
    pp_btn_reset_tooltip: '恢复基础参数：2模数，20齿标准直齿轮',
    pp_tab_basic: '齿廓基本参数',
    pp_tab_mating: '啮合仿真',
    pp_label_modulus: '模数 m (mm)',
    pp_tooltip_modulus: '齿轮尺寸的核心参数，模数越大轮廓越大',
    pp_modulus_desc: '常用标准模数系列: 1.0, 1.5, 2.0, 2.5, 3.0, 4.0 (支持任意非标小数设定)',
    pp_label_teeth: '齿数 z',
    pp_tooltip_teeth: '齿轮的牙齿个数，对于直齿圈，齿数越多角度越平缓',
    pp_teeth_desc: '输入范围: 4 - 300。少于 17 齿可能需要正变位参数来防止制造根切',
    pp_label_shift: '径向变位系数 x',
    pp_tooltip_shift: '变位系数。对于少齿数，正变位可避免根切，增强牙齿强度',
    pp_shift_desc: '正变位向外偏移增厚齿根；负变位反之。通常在少齿数时建议设置正变位 (如 +0.3)',
    pp_label_pressure_angle: '齿形角 / 压力角 α (°)',
    pp_tooltip_pressure_angle: '渐开线接触角，工业标准为 20度，部分低摩擦传动采用 14.5度',
    pp_label_addendum_coeff: '齿顶高系数 ha*',
    pp_tooltip_addendum_coeff: '标准齿轮一般为 1.0，短齿齿轮通常为 0.8',
    pp_label_clearance_coeff: '顶隙系数 c*',
    pp_tooltip_clearance_coeff: '防止顶切、排气及润滑空间，标准一般为 0.25',
    pp_label_fillet_coeff: '齿根过渡圆角系数 rf*',
    pp_tooltip_fillet_coeff: '齿根处生成的圆角半径比例，有助于均匀承载、在制造中提升抗脆性断裂强度，防止应力集中',
    pp_label_custom_da: '自定义齿顶圆直径 da (mm)',
    pp_tooltip_custom_da: '修改此项可直接手动调大/调小齿顶圆，通常减小齿顶圆以防止啮合卡滞、干涉',
    pp_std_da_val: '标准计算值：',
    pp_btn_reset_da: '重置',
    pp_btn_reset_da_tooltip: '恢复为标准计算值',
    pp_section_shaft: '轴孔与键槽规格孔设计',
    pp_label_shaft_dia: '主轴轴孔槽直径 (mm)',
    pp_tooltip_shaft_dia: '主运动传递轴孔的物理直径，设置 0 隐藏',
    pp_label_has_keyway: '启用机械传动防滑键槽',
    pp_tooltip_has_keyway: '在传动孔侧添加标准轴卡防滑槽',
    pp_label_keyway_width: '卡槽键宽 b (mm)',
    pp_tooltip_keyway_width: '键槽切削的标准物理宽度值',
    pp_label_keyway_depth: '卡槽键深 t (mm)',
    pp_tooltip_keyway_depth: '从轴孔圆弧向外凹陷挖切的深度值',
    pp_section_lightweight: '本体减重镂空腔排气设置',
    pp_label_spoke_type: '腔体镂空孔切削方式',
    pp_tooltip_spoke_type: '在齿腹中除去大块非必要重量的腔孔样式',
    pp_opt_spoke_none: '无本体减重孔 (Solid Face)',
    pp_opt_spoke_circle: '环向圆形排列打雷孔 (Circular Pattern)',
    pp_opt_spoke_sector: '骨格辐射扇形掏空 (Structural Sectors)',
    pp_label_spoke_count: '辐条与轻量孔连数量',
    pp_tooltip_spoke_count: '环向均匀分布的孔或空腔骨肋条数',
    pp_label_spoke_ratio: '掏空面积半径辐射占比',
    pp_tooltip_spoke_ratio: '内部空腔掏空边界的占比 (0.1 - 0.9)',
    pp_section_kerf: '激光气割缝割缝膨胀补偿',
    pp_label_kerf: '单边气动割缝宽度 (Kerf mm)',
    pp_tooltip_kerf: '激光由于焦点熔宽会引起实际割出齿厚偏薄。在此设置激光缝宽，程序会将外轮廓整体等距向外偏移此宽度的一半进行膨胀补偿，使实物 1:1 装配严丝合缝',
    pp_kerf_desc: '常用切割补偿范围: 0.05mm - 0.25mm',

    // Mating params english inside mating tab
    pp_mating_enable: '启用第二配对齿轮进行仿真',
    pp_mating_enable_desc: '在主窗口中生成配对啮合传动的预览',
    pp_mating_teeth: '配对齿轮齿数 z2',
    pp_mating_teeth_ideal: '理想传动配比数：',
    pp_mating_shift: '配对齿轮变位系数 x2',
    pp_mating_addendum: '配对齿顶高 ha2*',
    pp_mating_addendum_tooltip: '配对齿轮齿顶高系数，标准为 1.0',
    pp_mating_clearance: '配对顶隙 c2*',
    pp_mating_clearance_tooltip: '配对齿轮顶隙系数，标准为 0.25',
    pp_mating_custom_da: '配对自定义齿顶圆 da2 (mm)',
    pp_mating_custom_da_tooltip: '修改此项可手动微调配对齿轮的齿顶圆，通常减小它以防啮合干涉或卡滞',
    pp_mating_center_dist: '2齿中心距 a (mm)',
    pp_mating_center_dist_tooltip: '两齿轮在布局上的旋转圆心连线距离，修改以调节咬合间隙。留空则按照标准无侧隙轴间距公式定位。',
    pp_mating_shift_adjust: '双轮啮合干涉角微调 (度)',
    pp_mating_shift_adjust_tooltip: '旋转副齿轮以修复初次啮合齿顶切入阻卡',
    pp_mating_speed: '连动旋转快慢系数',
    pp_mating_speed_tooltip: '调整仿真播放物理转速快慢'
  },
  en: {
    // App Header & Layout
    app_subtitle: 'Mathematical modeling of standard/profile-shifted spur gears, featuring lightweight cutouts, laser cutting kerf compensation, and 1:1 SVG vectors direct download.',
    app_cad_ready: 'CAD_READY_TO_EXPORT (Metric physical calibration)',
    app_formula_ref: '🌐 Involute Gear Mathematical Formulas',
    app_formula_pitch: 'Pitch Diameter: ',
    app_formula_pitch_desc: ' (Reference standard for gear geometry)',
    app_formula_base: 'Base Circle Diameter: ',
    app_formula_base_desc: ' (Base cylinder from which the involute curves generate)',
    app_formula_addendum: 'Tip Diameter: ',
    app_formula_addendum_desc: ' (Outermost boundary cylinder of the teeth profile)',
    app_formula_dedendum: 'Root Diameter: ',
    app_formula_dedendum_desc: ' (Innermost boundary curve at the tooth bottom)',
    app_purpose_shift: '⚙️ Purpose of Profile Shift (Addendum Correction)',
    app_purpose_text: 'When the number of teeth is small (z < 17), standard gear hobbing manufacturing causes tool interference that thins the root structure. This defect, known as "undercutting", severely reduces tooth shear strength. To prevent this, setting a positive profile-shift coefficient x > 0 offsets the base circles outward, increasing the root thickness, eliminating undercut defects, and improving load transmission stamina.',
    app_copyright: '© 2026 High-Precision Gear Profile Generator. This CAD tool takes full responsibility for math derivations. Please pre-verify before hardware manufacturing or heavy torque tests.',

    // GearViewer Component
    gv_title: 'Live Kinematic Gear View',
    gv_mating_linkage: 'Mating Linkage:',
    gv_pause: 'Pause Animation',
    gv_simulate: 'Simulate Mesh',
    gv_zoom: 'Zoom:',
    gv_zoom_in: 'Zoom In',
    gv_zoom_out: 'Zoom Out',
    gv_reset_view: 'Reset Viewport',
    gv_primary_pitch: 'Primary Pitch Dia:',
    gv_primary_tip: 'Primary Tip Dia:',
    gv_mating_tip: 'Mating Tip Dia:',
    gv_center_dist: 'Center Distance:',
    gv_move_hint: 'Drag to scroll/pan. Use mouse wheel or pinch fingers to zoom.',

    // StatsPanel Component
    sp_title: 'Gear Engineering Calculations',
    sp_warning_title: '⚠️ Undercut Warning',
    sp_warning_text: 'Current teeth count z = {teeth} is below the theoretical limit {limit} required to avoid fabrication undercut. This thins the base curves, decreasing bending durability and contact ratio.',
    sp_suggestion_title: '💡 Engineering Fixes:',
    sp_suggestion_shift: 'Apply positive profile shift coefficient x ≥ ',
    sp_suggestion_teeth: 'Or increase teeth count to a minimum of ',
    sp_strength_ok: 'Tooth Strength Status: Stable',
    sp_strength_ok_desc: 'The tooth profile safely avoids the undercut zone; root thickness is optimal for robust shear capacity.',
    sp_heading_radial: '● Section Circles Reference',
    sp_tip_dia: 'Tip Diameter da',
    sp_tip_dia_desc: 'Outermost boundary cylinder of the gear teeth, da = d + 2 * (ha* + x) * m',
    sp_pitch_dia: 'Pitch Diameter d',
    sp_pitch_dia_desc: 'Standard geometrical design reference circle, d = m * z',
    sp_base_dia: 'Base Diameter db',
    sp_base_dia_desc: 'Base circle cylinder forming the involute roll curve, db = d * cos(alpha)',
    sp_dedendum_dia: 'Root Diameter df',
    sp_dedendum_dia_desc: 'Circle tracing the lowest bottom of tooth grooves, df = d - 2 * (ha* + c* - x) * m',
    sp_heading_micro: '● Microscopic Tooth Attributes',
    sp_tooth_thickness: 'Arc Tooth Thickness s',
    sp_circular_pitch: 'Circular Pitch p',
    sp_base_pitch: 'Base Pitch pb',
    sp_total_height: 'Total Tooth Height h',

    // ParameterPanel Component
    pp_title: 'Gear Parameter Settings',
    pp_btn_reset: 'Reset to Geometrical Std',
    pp_btn_reset_tooltip: 'Restore baseline values: Modulus 2, 20 Teeth standard spur gear',
    pp_tab_basic: 'Core Geometrical Inputs',
    pp_tab_mating: 'Mating mesh',
    pp_label_modulus: 'Modulus m (mm)',
    pp_tooltip_modulus: 'Central metric module defining tooth sizing. Greater modulus yields larger profiles.',
    pp_modulus_desc: 'Recommended series: 1.0, 1.5, 2.0, 2.5, 3.0, 4.0 (Any custom decimal value supported)',
    pp_label_teeth: 'Teeth Count z',
    pp_tooltip_teeth: 'Number of teeth. For standard pitches, more teeth generate gentler slopes.',
    pp_teeth_desc: 'Supported scope: 4 - 300. Less than 17 teeth requires a positive profile shift to avoid undercutting.',
    pp_label_shift: 'Profile Shift Coeff. x',
    pp_tooltip_shift: 'Shift coefficient. For small teeth counts, positive shift widens the tooth root, improving capacity.',
    pp_shift_desc: 'Positive shift pushes base circles outward to thicken roots; negative thins them. Strongly recommended for z < 17 (e.g., +0.3)',
    pp_label_pressure_angle: 'Pressure Angle α (°)',
    pp_tooltip_pressure_angle: 'Standard contact load angle. 20° is the common industrial standard; 14.5° is used to reduce friction.',
    pp_label_addendum_coeff: 'Addendum Coefficient ha*',
    pp_tooltip_addendum_coeff: 'Standard proportions recommend 1.0; stub teeth options use 0.8',
    pp_label_clearance_coeff: 'Clearance Coeff. c*',
    pp_tooltip_clearance_coeff: 'Prevent bottoming-out, facilitating lube flow and venting. Standard is 0.25',
    pp_label_fillet_coeff: 'Root Fillet Coeff. rf*',
    pp_tooltip_fillet_coeff: 'Blends root curves to prevent stress concentration and brittle failure under impact.',
    pp_label_custom_da: 'Override Tip Diameter da (mm)',
    pp_tooltip_custom_da: 'Manually stretch or thin the boundary tip. Helpful to reduce mating jam or tip friction.',
    pp_std_da_val: 'Standard Calc Value: ',
    pp_btn_reset_da: 'Undo',
    pp_btn_reset_da_tooltip: 'Restore standard calculated value',
    pp_section_shaft: 'Shaft Bore & Drive Keyway Slot',
    pp_label_shaft_dia: 'Bore Shaft Diameter (mm)',
    pp_tooltip_shaft_dia: 'Standard center axis hole diameter. Set 0 to disable.',
    pp_label_has_keyway: 'Add Torque Keyway Notch',
    pp_tooltip_has_keyway: 'Incise standard key slot adjacent to the bore to prevent slipping.',
    pp_label_keyway_width: 'Key Slot Width b (mm)',
    pp_tooltip_keyway_width: 'Standard mechanical physical width of Keyway',
    pp_label_keyway_depth: 'Key Slot Depth t (mm)',
    pp_tooltip_keyway_depth: 'Depression stroke extending from the bore perimeter outwards',
    pp_section_lightweight: 'Lightening Outlines & Weight Relief',
    pp_label_spoke_type: 'Relief Web Style',
    pp_tooltip_spoke_type: 'Excavates passive hub areas for lighter rotational inertia and modern styling.',
    pp_opt_spoke_none: 'Solid Gear Face',
    pp_opt_spoke_circle: 'Circular Radial Pocket Pattern',
    pp_opt_spoke_sector: 'Skeletal Triangular Sector Truss',
    pp_label_spoke_count: 'Rib Spokes Number',
    pp_tooltip_spoke_count: 'Quantity of radially arranged cutout segments or strengthening ribs',
    pp_label_spoke_ratio: 'Relief Inner Radius Ratio',
    pp_tooltip_spoke_ratio: 'The boundary proportion of weight cutout radius (0.1 - 0.9)',
    pp_section_kerf: 'Laser Scurrying Kerf Offset',
    pp_label_kerf: 'Single-Side Kerf Offset (mm)',
    pp_tooltip_kerf: 'Laser cutting beam melt paths make gears thin and loose. Specifying your laser width here offsets the vector outwards by half the kerf value, ensuring tight 1:1 tolerance fit.',
    pp_kerf_desc: 'Typical compensation range: 0.05mm - 0.25mm',

    // Mating params inside mating tab
    pp_mating_enable: 'Enable Secondary Mating Gear Simulation',
    pp_mating_enable_desc: 'Generates a virtual intermeshed partner gear in the main viewport.',
    pp_mating_teeth: 'Mating Teeth Count z2',
    pp_mating_teeth_ideal: 'Ideal Transmission Ratio:',
    pp_mating_shift: 'Mating Profile Shift Coeff. x2',
    pp_mating_addendum: 'Mating Addendum ha2*',
    pp_mating_addendum_tooltip: 'Partnership addendum coefficient. Standard is 1.0',
    pp_mating_clearance: 'Mating Clearance c2*',
    pp_mating_clearance_tooltip: 'Partnership clearance coefficient. Standard is 0.25',
    pp_mating_custom_da: 'Mating Override Tip da2 (mm)',
    pp_mating_custom_da_tooltip: 'Override the partners tip boundary diameter. Reduces tooth engagement jam.',
    pp_mating_center_dist: 'Mating Center Distance a (mm)',
    pp_mating_center_dist_tooltip: 'Center-to-center axle distance. Tweak to change backlash profile. Blank uses standard zero-backlash mesh formula.',
    pp_mating_shift_adjust: 'Active Engagement Alignment (deg)',
    pp_mating_shift_adjust_tooltip: 'Rotational micro-indexing for the secondary gear to solve overlapping fitment.',
    pp_mating_speed: 'Spin Velocity Coefficient',
    pp_mating_speed_tooltip: 'Scale simulation playback rotation speed'
  }
};
